### ISSUE TITLE
Create a small static version of linuxmint.com

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint-design#1]
We need  to add a small static HTML/CSS version of linuxmint.com to this repository, so that artists can work on it.

**Comment by Sirikon** [comment]
A question about the actual version of linuxmint.com, is it any CMS/Framework or is a from-scratch PHP web page?

**Comment by clefebvre** [comment]
It's made from scratch using php and mysql mostly. A few areas are cached as well.

**Comment by Sirikon** [comment]
@clefebvre Then, for the new webpage, will we re-use the actual PHP project or are we going to make a new one?, what do you think?

**Comment by clefebvre** [comment]
No, I'd like artists to work on static material and focus only on the look, presentation and navigation, not on the backend and not on the PHP side of things.

For instance for linuxmint.com, you could either:

- modify the HTML/CSS version of linuxmint.com that is in this git repository
- create a brand new HTML/CSS webpage, or a PSD design, or even a mockup to discuss new design ideas

You can create a new issue to post your mockup, or a pull request to attach your webpage. 

Personally I'd prefer if you made/explored new designs (rather than modify the existing one). The main reason I added the HTML/CSS version of linuxmint.com to this repository wasn't for people to modify it or improve it, but so you could easily grab elements of CSS or pictures you might want to reuse or get inspiration from.

**Comment by Sirikon** [comment]
Great, I think that make a totally new webpage (front-end) is the correct way to work too.
